# Generated by Django 5.1.3 on 2026-01-27 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='The hospital this user belongs to (required for Admin, Doctor, Patient)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hospitals.hospital'),
        ),
    ]
