# Generated by Django 5.1.3 on 2026-01-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_hospital'),
    ]

    operations = [
    ]
