# Generated by Django 5.1.3 on 2026-01-28 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_appointment_call_token"),
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(max_length=200)),
                ("agora_token", models.TextField()),
                ("doctor_joined", models.BooleanField(default=False)),
                ("patient_joined", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_session",
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
    ]
