# Generated by Django 5.1.3 on 2026-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_notes',
            field=models.TextField(blank=True, help_text='Doctor findings and outcome'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('done', 'Done')], default='scheduled', max_length=20),
        ),
    ]
