# Generated by Django 5.1.3 on 2026-01-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointment_consultation_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="call_token",
            field=models.CharField(
                blank=True,
                help_text="4-digit token for video call",
                max_length=4,
                null=True,
            ),
        ),
    ]
